## Estadistica Aplicada

Sesion 2 - 9 de agosto

Bárbara Govea Serna 1902869

Una lista en python es una colección de objetos que pueden ser de distinto tipo 

In [78]:
# Crearemos una lista
alumno1=['Juan','Perez',17]

In [5]:
type(alumno1)

list

In [6]:
alumno1

['Juan', 'Perez', 17]

In [8]:
estadistica_g4=['Dania','Carla','Alan','Vania']

In [9]:
estadistica_g4

['Dania', 'Carla', 'Alan', 'Vania']

In [10]:
estadistica_g4[2]

'Alan'

In [11]:
estadistica_g4[0]

'Dania'

In [12]:
estadistica_g4[0],estadistica_g4[2]

('Dania', 'Alan')

In [13]:
estadistica_g4[0:3]

['Dania', 'Carla', 'Alan']

In [22]:
yo_en_FCFM=['Barbara','LA',7,90.5]

In [23]:
mi_promedio=yo_en_FCFM[3]
mi_carrera=yo_en_FCFM[1]

In [24]:
print(mi_carrera,mi_promedio)

LA 90.5


## Librerias/Modulos/Paqueteria
Una libreria en python es un conjunto de codigos que le dice a Python como hacer determinadas cosas

Una libreria primero se instala (única vez), y luego se le indica a python que la use

## YFINANCE

In [33]:
#Codigo para instalar libreria YFINANCE
#pip install yfinance

In [35]:
#CODIGO PARA MANDAR A LLAMAR LA LIBRERIA y LA RENOMBRAMOS COMO yf
import yfinance as yf

In [40]:
#CODIGO PARA DESCARGAR LAS ACCIONES DE la libreria YF
##yf.download() 

## NUMPY
Sirve para manejar numeros en Python

In [39]:
#CODIGO PARA MANDAR A LLAMAR LA LIBRERIA y LA RENOMBRAMOS COMO np
import numpy as np

La estructura basica de numpy son los arreglos (arrays)

Un arreglo es una coleccion de objetos del MISMO TIPO (en este caso son numericos)

In [44]:
# Crear una lista con las ventas de paleta

ventas = [12,23,34,45,56]

# Convertiremos la lista a uyn arreglo de Numpy para poder utilizar las funciones de numpy, como lo son la media, entre otras

ventas = np.array(ventas)

In [45]:
# Corroboramos el tipo
type(ventas)

numpy.ndarray

In [46]:
# Para obtener el promedio 
np.mean(ventas)

34.0

In [47]:
# Para realizar una suma 
np.sum(ventas)

170

In [49]:
# Obtener el máximo de nuestro arreglo
np.max(ventas)

56

In [50]:
# Obtener el minimo de nuestro arreglo
np.min(ventas)

12

In [51]:
# Para obtener la varianza poblacional
# Python utiliza una formula diferente, debemos especificar el ddof, si no lo ponemos dara por sentado el 0
np.var(ventas,0)

242.0

In [53]:
# Para obtener la varianza muestral 
# En este caso el ddof debe ser 1, para que en el denominador quede n-1
np.var(ventas,ddof=1)

302.5

In [57]:
# Para obtener la desviacion poblacional
# Python utiliza una formula diferente, debemos especificar el ddof, si no lo ponemos dara por sentado el 0
np.std(ventas,0)

15.556349186104045

In [56]:
# Para obtener la desviacion muestral 
# En este caso el ddof debe ser 1, para que en el denominador quede n-1
np.std(ventas,ddof=1)

17.392527130926087

VECTOR

In [59]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [61]:
#El primero indicara donde empieza, el segundo donde termina menos 1, y el tercero de cuanto en cuanto vaya
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [63]:
#Si quiero un vector de zeros
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
# Si quiero un vector de unos
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [65]:
# Quiero un vector de 6 10s, el primer elemento indica el tamaño de muestra y el segundo elemento indica el numero a repetir
np.full(6,10)

array([10, 10, 10, 10, 10, 10])

In [71]:
# Quiero un vector de numeros randoms
# El primer y segundo elemento es el rango, osease entre 0 y 20
# El tercer elemento es la cantidad de muestra
np.random.seed(12) # Siempre debemos fijar la semilla, puede ser cualquier cosa, en este caso pusimos el 12
aleatorios = np.random.randint(0,20,10) # El 20 tambien lo toma, proviene de una distribucion uniforme 

In [72]:
aleatorios

array([11,  6, 17,  2,  3,  3, 12, 16, 17,  5])

In [74]:
# Ordenar nuestros numeros aleatorios
aleatorios = np.sort(aleatorios)

In [75]:
aleatorios

array([ 2,  3,  3,  5,  6, 11, 12, 16, 17, 17])

In [76]:
# En un arreglo podemos seleccionar igual que en una lista
aleatorios[4]

6

In [77]:
# En este caso podemos realizarlo con comas, en las listas no podemos hacer esto. PERO DEBEMOS PONER DOBLE CORCHETE
aleatorios[[0,4]]

array([2, 6])

In [79]:
# Condicionales
# Estamos diciendo, imprime, del arreglo aleatorios, solo con los mayores que 10
aleatorios [aleatorios>10]

array([11, 12, 16, 17, 17])

In [80]:
# Condicionales
# Estamos diciendo, imprime, del arreglo aleatorios, solo con los menos que 7
aleatorios[aleatorios<7]

array([2, 3, 3, 5, 6])

In [84]:
# Vamos a generar una nueva lista y trabajaremos con ella por la función y por: 

numeros = [1.2,2.34,5.18]

### FUNCION

In [85]:
# Lo convertiremos a un arreglo
# Obtendremos la media 
# Redondearemos a 2 decimales

round(np.mean(np.array(numeros)),2)



2.91

### METODO

In [90]:
# Esta es la que se recomienda mas a comparacion de la otra
np.array(numeros).mean().round(2)

2.91